import { ISshLogs } from "../models/types/monitors";

export const renewalLogs: ISshLogs = [
	{ type: "input", text: "npm install" },
	{
		type: "output",
		text: "npm WARN saveError ENOENT: no such file or directory, open '/home/server/package.json'",
	},
	{ type: "output", text: "npm WARN enoent ENOENT: no such file or directory, open '/home/server/package.json'" },
	{ type: "output", text: "npm WARN server No description" },
	{ type: "output", text: "npm WARN server No repository field." },
	{ type: "output", text: "npm WARN server No README data" },
	{ type: "output", text: "npm WARN server No license field." },
	{ type: "output", text: "up to date in 1.035s" },
	{ type: "output", text: "found 0 vulnerabilities" },
	{ type: "input", text: "npm install" },
	{
		type: "output",
		text: "npm WARN saveError ENOENT: no such file or directory, open '/home/server/package.json'",
	},
	{ type: "output", text: "npm WARN enoent ENOENT: no such file or directory, open '/home/server/package.json'" },
	{ type: "output", text: "npm WARN server No description" },
	{ type: "output", text: "npm WARN server No repository field." },
	{ type: "output", text: "npm WARN server No README data" },
	{ type: "output", text: "npm WARN server No license field." },
	{ type: "output", text: "up to date in 1.035s" },
	{ type: "output", text: "found 0 vulnerabilities" },
	{ type: "input", text: "npm install" },
	{
		type: "output",
		text: "npm WARN saveError ENOENT: no such file or directory, open '/home/server/package.json'",
	},
	{ type: "output", text: "npm WARN enoent ENOENT: no such file or directory, open '/home/server/package.json'" },
	{ type: "output", text: "npm WARN server No description" },
	{ type: "output", text: "npm WARN server No repository field." },
	{ type: "output", text: "npm WARN server No README data" },
	{ type: "output", text: "npm WARN server No license field." },
	{ type: "output", text: "up to date in 1.035s" },
	{ type: "output", text: "found 0 vulnerabilities" },
	{ type: "input", text: "npm install" },
	{
		type: "output",
		text: "npm WARN saveError ENOENT: no such file or directory, open '/home/server/package.json'",
	},
	{ type: "output", text: "npm WARN enoent ENOENT: no such file or directory, open '/home/server/package.json'" },
	{ type: "output", text: "npm WARN server No description" },
	{ type: "output", text: "npm WARN server No repository field." },
	{ type: "output", text: "npm WARN server No README data" },
	{ type: "output", text: "npm WARN server No license field." },
	{ type: "output", text: "up to date in 1.035s" },
	{ type: "output", text: "found 0 vulnerabilities" },
];
